apiVersion: apps/v1
kind: Deployment
metadata:
  name: learner-deployment
  namespace: chou-pruebas
  labels:
    app: learner
spec:
  replicas: 2
  selector:
    matchLabels:
      app: learner
  template:
    metadata:
      labels:
        app: learner
    spec:
      containers:
      - name: learner
        image: schouhy/minitchess-alphazero:1
        command: ["python", "-m", "app.learner"]
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          name: flask
          protocol: TCP
        env:
        - name: MASTER_URL
          value: "http://master-of-puppets-service:5000"
        - name: WEIGHTS_PATH
          value: /data/weights.sd
        - name: USERID
          value: dalearner
        - name: KEY
          value: akey
