apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
spec:
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
      - name: mosquitto
        image: eclipse-mosquitto:2.0
        #        resources:
        #          requests:
        #            cpu: "50m"
        #          limits:
        #            memory: "128Mi"
        #            cpu: "500m"
        ports:
        - containerPort: 1883
        volumeMounts:
        - name: config-volume
          mountPath: /mosquitto/config/mosquitto.conf
          subPath: mosquitto.conf
        - name: passwd-volume
          mountPath: /mosquitto/config/passwd
          subPath: passwd
          readOnly: true
      volumes:
      - name: config-volume
        configMap:
          name: mosquitto-config 
      - name: passwd-volume
        secret:
          secretName: mosquitto-passwd

