apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: mosquitto
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
        #   tls:
        #   - hosts:
        #       - pubsub-rl.k8s.eryx.co
        #     secretName: pubsub-rl-tls
  rules:
  - host: pubsub-rl.k8s.eryx.co
    http:
      paths:
      - path: /
        backend:
          serviceName: mosquitto
          servicePort: 1883
