apiVersion: apps/v1
kind: Deployment
metadata:
  name: puppet-deployment
  namespace: chou-pruebas
  labels:
    app: puppet
spec:
  replicas: 2
  selector:
    matchLabels:
      app: puppet
  template:
    metadata:
      labels:
        app: puppet
    spec:
      containers:
      - name: puppet
        image: schouhy/minitchess-alphazero:1
        command: ["python", "-m", "app.puppet"]
        imagePullPolicy: Always
        env:
        - name: MQTT_BROKER_HOST
          value: pubsub-rl.cloud.shiftr.io
        - name: LEARNER_TOPIC
          value: minitchess-alphazero/learner
        - name: MQTT_USERNAME
          value: pubsub-rl
        - name: MQTT_PASSWORD
          value: FM0QBm3vm3RiPf1d
        - name: PUBLISH_EPISODE_TOPIC
          value: minitchess-alphazero/episodes
        - name: LOGGER_URL
          value: http://rlweb.k8s.eryx.co
