apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minitchess-simplealphazero-pvc
  labels:
    # insert any desired labels to identify your claim
    app: pvc
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      # The amount of the volume's storage to request
      storage: 5Gi

